<?php

namespace Database\Seeders;

use App\Models\Cultivo;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class CultivoSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $cultivos = [
            [
                'nombre' => 'Frambuesa',
                'descripcion' => 'Fruta de sabor dulce y color rojo intenso, cultivada en climas templados.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 7,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Aguacate',
                'descripcion' => 'Fruto de gran valor nutricional, popular en la gastronomía mexicana.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 10,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Zarzamora',
                'descripcion' => 'Baya de sabor ácido-dulce muy utilizada en mermeladas.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 8,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Fresa',
                'descripcion' => 'Fruta roja de sabor dulce, rica en antioxidantes.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 10,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Arándano',
                'descripcion' => 'Pequeña fruta azul, conocida por sus beneficios a la salud ocular.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 7,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Jitomate',
                'descripcion' => 'Ingrediente esencial en la cocina mexicana, rico en licopeno.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 10,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Maíz',
                'descripcion' => 'Grano básico de la dieta mexicana, adaptable a múltiples climas.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 7,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Arroz',
                'descripcion' => 'Cereal esencial en la alimentación mundial, cultivado en suelos húmedos.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 8,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Frijol',
                'descripcion' => 'Leguminosa rica en proteínas, esencial en la dieta latinoamericana.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 10,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Trigo',
                'descripcion' => 'Cereal ampliamente cultivado para la elaboración de pan y harinas.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 6,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Caña de azúcar',
                'descripcion' => 'Planta tropical utilizada en la producción de azúcar y biocombustibles.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 14,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café',
                'descripcion' => 'Cultivo tropical que produce granos para una de las bebidas más consumidas en el mundo.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => null,
                'tipo_vida' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Higo',
                'descripcion' => 'Fruta carnosa y dulce con alto contenido de fibra.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 10,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Prueba',
                'descripcion' => 'Tipo de Cultivo utilizado con fines de prueba o datos temporales.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 7,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Agave',
                'descripcion' => 'Planta suculenta utilizada en la producción de tequila y mezcal.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 8,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Uva de Mesa',
                'descripcion' => 'Fruta dulce cultivada principalmente para consumo fresco.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 10,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Chile Habanero',
                'descripcion' => 'Chile muy picante ampliamente utilizado en la cocina y salsas.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 12,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Papaya',
                'descripcion' => 'Fruta tropical rica en enzimas digestivas y antioxidantes.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 16,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Sorgo',
                'descripcion' => 'Cereal resistente a la sequía, utilizado como alimento y forraje.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 10,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Platano / Banano',
                'descripcion' => 'Fruta tropical rica en potasio y energía, ampliamente consumida en todo el mundo.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 15,
                'tipo_vida' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Tabaco',
                'descripcion' => 'Planta cultivada por sus hojas, utilizadas en la fabricación de productos de tabaco.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 18,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pimiento',
                'descripcion' => 'Fruto comestible de sabor suave o picante, ampliamente usado en cocina.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 16,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pepino',
                'descripcion' => 'Hortaliza refrescante con alto contenido de agua, ideal para ensaladas.',
                'imagen' => null,
                'icono' => null,
                'temp_base_calor' => 18,
                'tipo_vida' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];

        Cultivo::insert($cultivos);
    }
}
