<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Plaga;
use Carbon\Carbon;

class PlagaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        Plaga::insert([
            [
                'nombre' => 'Barrenador de Ramas del Aguacate',
                'slug' => 'barrenador-de-ramas-del-aguacate',
                'imagen' => 'uploads/plagas/4.png',
                'descripcion' => 'Copturus aguacatae Kissinger',
                'posicion1' => 0,
                'posicion2' => 80,
                'posicion3' => 160,
                'posicion4' => 231,
                'posicion5' => 320,
                'posicion6' => 460,
                'umbral_min' => 10,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 460,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Barrenador pequeño de la semilla del aguacate',
                'slug' => 'barrenador-pequeno-semilla-aguacate',
                'imagen' => '',
                'descripcion' => 'Conotrachelus perseae Barber',
                'posicion1' => 0,
                'posicion2' => 30,
                'posicion3' => 60,
                'posicion4' => 90,
                'posicion5' => 120,
                'posicion6' => 160,
                'umbral_min' => 10,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 160,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Palomilla barrenadora de la semilla del aguacate Stenoma catenifer',
                'slug' => 'palomilla-barrenadora-semilla-aguacate-stenoma-cat',
                'imagen' => '',
                'descripcion' => 'Lepidoptera:Elachistidae',
                'posicion1' => 0,
                'posicion2' => 60,
                'posicion3' => 120,
                'posicion4' => 180,
                'posicion5' => 240,
                'posicion6' => 328,
                'umbral_min' => 9,
                'umbral_max' => 28,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 328,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Trips del aguacate Scirtothrips perseae',
                'slug' => 'trips-del-aguacate-scirtothrips-perseae',
                'imagen' => '',
                'descripcion' => 'Thysanoptera: Thripidae',
                'posicion1' => 0,
                'posicion2' => 10,
                'posicion3' => 25,
                'posicion4' => 38,
                'posicion5' => 50,
                'posicion6' => 70,
                'umbral_min' => 7,
                'umbral_max' => 25,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 70,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Trips de las Berries',
                'slug' => 'trips-de-las-berries',
                'imagen' => '',
                'descripcion' => 'Thysanoptera: Thripidae',
                'posicion1' => 0,
                'posicion2' => 10,
                'posicion3' => 25,
                'posicion4' => 38,
                'posicion5' => 50,
                'posicion6' => 70,
                'umbral_min' => 7,
                'umbral_max' => 25,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 70,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Frankiniella Occidentalis',
                'slug' => 'frankiniella-occidentalis',
                'imagen' => '',
                'descripcion' => 'Trips',
                'posicion1' => 0,
                'posicion2' => 15,
                'posicion3' => 30,
                'posicion4' => 50,
                'posicion5' => 70,
                'posicion6' => 90,
                'umbral_min' => 10,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 90,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Gusano Cogollero',
                'slug' => 'gusano-cogollero',
                'imagen' => '',
                'descripcion' => 'Cogollero',
                'posicion1' => 0,
                'posicion2' => 80,
                'posicion3' => 160,
                'posicion4' => 240,
                'posicion5' => 300,
                'posicion6' => 372,
                'umbral_min' => 14,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 372,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Gusano soldado',
                'slug' => 'gusano-soldado',
                'imagen' => '',
                'descripcion' => 'Pseudaletia unipunctua',
                'posicion1' => 0,
                'posicion2' => 200,
                'posicion3' => 400,
                'posicion4' => 600,
                'posicion5' => 800,
                'posicion6' => 1000,
                'umbral_min' => 10,
                'umbral_max' => 35,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 1000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Gusano trozador',
                'slug' => 'gusano-trozador',
                'imagen' => '',
                'descripcion' => 'Agrotis ipsilon, Hufnagel',
                'posicion1' => 0,
                'posicion2' => 120,
                'posicion3' => 240,
                'posicion4' => 360,
                'posicion5' => 480,
                'posicion6' => 600,
                'umbral_min' => 10,
                'umbral_max' => 35,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 600,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Arañuela Oligonychus spp',
                'slug' => 'aranjuela-oligonychus-spp',
                'imagen' => '',
                'descripcion' => 'Tetranychus spp',
                'posicion1' => 0,
                'posicion2' => 15,
                'posicion3' => 30,
                'posicion4' => 45,
                'posicion5' => 60,
                'posicion6' => 80,
                'umbral_min' => 15,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 80,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Cochuela del frijol',
                'slug' => 'cochuela-del-frijol',
                'imagen' => '',
                'descripcion' => 'Epilachna varivestis Mulsant',
                'posicion1' => 0,
                'posicion2' => 60,
                'posicion3' => 120,
                'posicion4' => 180,
                'posicion5' => 240,
                'posicion6' => 300,
                'umbral_min' => 10,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 300,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Barrenador del arroz',
                'slug' => 'barrenador-del-arroz',
                'imagen' => '',
                'descripcion' => 'Chilo suppressalis, Walker',
                'posicion1' => 0,
                'posicion2' => 250,
                'posicion3' => 500,
                'posicion4' => 750,
                'posicion5' => 1000,
                'posicion6' => 1300,
                'umbral_min' => 10,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 1300,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pulgon verde del trigo',
                'slug' => 'pulgon-verde-del-trigo',
                'imagen' => '',
                'descripcion' => 'Schiyaphis graminum Rondani',
                'posicion1' => 0,
                'posicion2' => 80,
                'posicion3' => 160,
                'posicion4' => 240,
                'posicion5' => 320,
                'posicion6' => 400,
                'umbral_min' => 10,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 400,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Gusano/mosca de la fruta',
                'slug' => 'gusano-mosca-de-la-fruta',
                'imagen' => '',
                'descripcion' => 'Mosca de la fruta',
                'posicion1' => 0,
                'posicion2' => 100,
                'posicion3' => 200,
                'posicion4' => 300,
                'posicion5' => 400,
                'posicion6' => 500,
                'umbral_min' => 20,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 600,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pulgón de los Berries',
                'slug' => 'pulgon-de-los-berries',
                'imagen' => '',
                'descripcion' => 'Pulgon',
                'posicion1' => 0,
                'posicion2' => 50,
                'posicion3' => 120,
                'posicion4' => 200,
                'posicion5' => 250,
                'posicion6' => 300,
                'umbral_min' => 20,
                'umbral_max' => 25,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 300,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Escarabajo de las hojas de los Berries',
                'slug' => 'escarabajo-hojas-berries',
                'imagen' => '',
                'descripcion' => 'Escarabajo',
                'posicion1' => 0,
                'posicion2' => 60,
                'posicion3' => 120,
                'posicion4' => 180,
                'posicion5' => 240,
                'posicion6' => 400,
                'umbral_min' => 20,
                'umbral_max' => 29,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 400,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Chinches Manchadas',
                'slug' => 'chinches-manchadas',
                'imagen' => '',
                'descripcion' => 'Chinches',
                'posicion1' => 0,
                'posicion2' => 60,
                'posicion3' => 120,
                'posicion4' => 180,
                'posicion5' => 240,
                'posicion6' => 300,
                'umbral_min' => 25,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 283,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Escamas del aguacate',
                'slug' => 'escamas-del-aguacate',
                'imagen' => '',
                'descripcion' => 'Escamas armadas',
                'posicion1' => 0,
                'posicion2' => 30,
                'posicion3' => 60,
                'posicion4' => 90,
                'posicion5' => 120,
                'posicion6' => 154,
                'umbral_min' => 20,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 154,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Araña Roja',
                'slug' => 'arana-roja',
                'imagen' => '',
                'descripcion' => 'Araña Roja',
                'posicion1' => 0,
                'posicion2' => 20,
                'posicion3' => 40,
                'posicion4' => 60,
                'posicion5' => 80,
                'posicion6' => 90,
                'umbral_min' => 24,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 90,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Gusano de la Raíz',
                'slug' => 'gusano-de-la-raiz',
                'imagen' => '',
                'descripcion' => 'Gusano Raíz',
                'posicion1' => 0,
                'posicion2' => 80,
                'posicion3' => 160,
                'posicion4' => 240,
                'posicion5' => 320,
                'posicion6' => 450,
                'umbral_min' => 20,
                'umbral_max' => 30,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 450,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Picudo del Agave',
                'slug' => 'picudo-del-agave',
                'imagen' => '',
                'descripcion' => 'Scyphophorus acupunctatus',
                'posicion1' => 0,
                'posicion2' => 450,
                'posicion3' => 750,
                'posicion4' => 1100,
                'posicion5' => 1400,
                'posicion6' => 1700,
                'umbral_min' => 12,
                'umbral_max' => 25,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 1700,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Mosca del Agave',
                'slug' => 'mosca-del-agave',
                'imagen' => '',
                'descripcion' => 'Mosca del agave',
                'posicion1' => 0,
                'posicion2' => 200,
                'posicion3' => 700,
                'posicion4' => 1000,
                'posicion5' => 1500,
                'posicion6' => 2000,
                'umbral_min' => 14,
                'umbral_max' => 29,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 2000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Trips del Agave',
                'slug' => 'trips-del-agave',
                'imagen' => '',
                'descripcion' => 'Trips del Agave',
                'posicion1' => 0,
                'posicion2' => 60,
                'posicion3' => 120,
                'posicion4' => 160,
                'posicion5' => 220,
                'posicion6' => 340,
                'umbral_min' => 10,
                'umbral_max' => 37,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 340,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Acaros del Agave',
                'slug' => 'acaros-del-agave',
                'imagen' => '',
                'descripcion' => 'Brevipalpus phoenicis',
                'posicion1' => 0,
                'posicion2' => 50,
                'posicion3' => 110,
                'posicion4' => 150,
                'posicion5' => 200,
                'posicion6' => 260,
                'umbral_min' => 10,
                'umbral_max' => 40,
                'alarmas_acumuladas' => null,
                'unidades_calor_ciclo' => 290,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);
    }
}
