<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'nombre' => 'admin',
                'email' => 'admin@appgricola.com',
                'password' => '$2y$12$gRYXH5bAQ.xoWa2VEZjaIO.dT3y7vtCxs61m.OH2GD9EGQxw4oTdO',
                'cliente_id' => null,
                'role_id' => 1,
                'remember_token' => 'R2VDODBfhsqzq3wBqFrZQBXC8YKTqU464lD2uWVNvpULO5Iwg4lMlu56S6f8',
                'created_at' => '2018-09-11 20:22:42',
                'updated_at' => '2018-09-11 20:22:42',
                'status' => 1
            ],
            [
                'id' => 2,
                'nombre' => 'Saul Ramos',
                'email' => 'saulramosm@hotmail.com',
                'password' => '$2y$12$QKo//gCjGSVmD.IC.p2ESeOQupVMt07Wk5nMCFq7PeJngduLB7emG',
                'cliente_id' => 4,
                'role_id' => 3,
                'remember_token' => 'CmNgdaLBaLLkExMa94ZX0cqSjNTUz84diGUsHJJtGQhBQcQepNkIItBNo5nB1',
                'created_at' => '2018-09-12 01:22:42',
                'updated_at' => '2018-09-12 01:22:42',
                'status' => 1
            ],
            [
                'id' => 4,
                'nombre' => 'Epitacio Robledo',
                'email' => 'epitaciorobledo@civat.org',
                'password' => '$2y$10$NrKF9TKAjX6XRB8ZRrXot.gsE4gXhnLhTseKQIsRlpeifoH0UanjW',
                'cliente_id' => 5,
                'role_id' => 3,
                'remember_token' => '7LywiVYbcKh7dr8gcbVFgovC1lTNjtNnaRE4tnjpRBCLQjYi2BZLIk6xmChe',
                'created_at' => '2019-11-12 06:00:00',
                'updated_at' => '2019-11-12 06:00:00',
                'status' => 1
            ],
            [
                'id' => 5,
                'nombre' => 'Epitacio Robledo',
                'email' => 'wolinacruz@gmail.com',
                'password' => '$2y$12$zaAmO5img85m/HpohZUwCeyG1jexZs5CN/yx4.q146Z6nmEW3CQlS',
                'cliente_id' => 5,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2019-11-12 06:00:00',
                'updated_at' => '2019-11-12 06:00:00',
                'status' => 1
            ],
            [
                'id' => 6,
                'nombre' => 'Efraín Baltazar - Grupo Cerritos',
                'email' => 'efrain.baltazar@glc.mx',
                'password' => '$2y$12$ZSFABq7keP2iIKk9d099Ce.VG19dqUFhiiSQ4ttzzW1/LewGF55vO',
                'cliente_id' => 6,
                'role_id' => 3,
                'remember_token' => 'EII4FJUl4wI3GoB7JRpzHF5Vq6hLGVC1Mgof8uzpuvR35AtI7XrsRPs07Ce2',
                'created_at' => '2020-01-06 06:00:00',
                'updated_at' => '2020-01-06 06:00:00',
                'status' => 1
            ],
            [
                'id' => 7,
                'nombre' => 'Jesus Elvira',
                'email' => 'pruebanpk',
                'password' => '$2a$12$00BtbmBn8yIhdEJXGHC0/OrW8QvwTlZUON5Ro9.JZFuuXkyhd3LRW',
                'cliente_id' => 7,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2020-01-27 06:00:00',
                'updated_at' => '2020-01-27 06:00:00',
                'status' => 1
            ],
            [
                'id' => 8,
                'nombre' => 'Raúl M. Trejo Luna ',
                'email' => 'estrada.aguilar.ja@gmail.com',
                'password' => '$2b$10$YovU16nyIxqZJ88E2Ak5duDn6xD1f0ZJQ0c03ChBqIV5AXyx34Fyi',
                'cliente_id' => 8,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2020-05-02 05:00:00',
                'updated_at' => '2020-05-02 05:00:00',
                'status' => 1
            ],
            [
                'id' => 9,
                'nombre' => 'Nombre prueba 1',
                'email' => 'correo@correo.com',
                'password' => '$2y$10$Qpd4PkmSybHhLFWFd2oSPey6WNXnTkrxgbAegBPROpnoB503HMst.',
                'cliente_id' => 10,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2020-05-18 21:03:35',
                'updated_at' => '2020-05-18 21:03:35',
                'status' => 1
            ],
            [
                'id' => 10,
                'nombre' => 'Miguél Trejo',
                'email' => 'cycasasc.admon@gmail.com',
                'password' => '$2y$10$JxOYdtWXAwJnlIdZfR.asOEigknNBEw1zCqXgxU.jMkMeEsNBKcIm',
                'cliente_id' => 11,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2020-05-18 22:40:40',
                'updated_at' => '2020-05-18 22:40:40',
                'status' => 1
            ],
            [
                'id' => 11,
                'nombre' => 'demo',
                'email' => 'demo@avansys.com.mx',
                'password' => '$2y$12$bhP9JpW9BS1fDmC.CJxdzu8SDzSV6H22Cgd74ofTF8rVNjXX/Wu1.',
                'cliente_id' => 11,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2020-10-22 18:04:48',
                'updated_at' => '2020-10-22 18:04:48',
                'status' => 1
            ],
            [
                'id' => 12,
                'nombre' => 'AEM',
                'email' => 'aem',
                'password' => '$2y$10$9I8AW5BPg8pIsIi1.Ala3ePFwQIDW2l6GaLVKzx.RalP04nVZ5IsW',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2020-12-21 15:34:09',
                'updated_at' => '2020-12-21 15:34:09',
                'status' => 1
            ],
            [
                'id' => 13,
                'nombre' => 'Dr. Olmos',
                'email' => 'dr.olmos',
                'password' => '$2y$10$HVf3l2fNCCKnwUI4yoJJheLAnwFYmf3uRXazgObSkwn0viwPNPlYi',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2021-01-19 18:33:17',
                'updated_at' => '2021-01-19 18:33:17',
                'status' => 1
            ],
            [
                'id' => 14,
                'nombre' => 'Héctor Ricardo Cervantes Jimenez',
                'email' => 'ricardo.corralillos1@gmail.com',
                'password' => '$2y$10$SQaCdKPFGxcaUfW7Y4dtoOKRz606Wrg0WAKkwU2/iZqBnWiOo2IGq',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2021-01-20 02:16:06',
                'updated_at' => '2022-06-01 18:47:46',
                'status' => 1
            ],
            [
                'id' => 15,
                'nombre' => 'Osvaldo',
                'email' => 'v@hotmail.com',
                'password' => '$2y$10$.LfSC6sg6LnQ1VeneVnr7u1Xif5kRDbHY5jJQ9aJF3c.PmvjHcH.i',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2021-01-20 02:16:35',
                'updated_at' => '2021-01-24 08:13:48',
                'status' => 0
            ],
            [
                'id' => 16,
                'nombre' => 'Silviano Gallardo Ramirez',
                'email' => 'silviano.gallardo@gmail.com',
                'password' => '$2y$10$48Kg/qBOQ4X6e6mWEa7QmujN4zYsg8u..eq8LEwyVHvKPt9lFmDVG',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2021-01-20 02:25:02',
                'updated_at' => '2024-06-17 21:57:09',
                'status' => 1
            ],
            [
                'id' => 17,
                'nombre' => 'Civat',
                'email' => 'contacto@civat.org',
                'password' => '$2a$12$InxcCPB2ro1esyPwWqaqwuwN0zD3iKy0l9XxhNFB7ZBZr2aaI.jkO',
                'cliente_id' => 5,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2021-01-21 22:25:21',
                'updated_at' => '2022-02-10 16:58:55',
                'status' => 1
            ],
            [
                'id' => 18,
                'nombre' => 'Pro',
                'email' => 'pro@pro.com',
                'password' => '$2y$10$c4x5mWwFjzjyOUiSF/j8c.IOF3j1CYv5Nl9Tf3A77H.wThc2ADfzy',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2021-01-24 07:57:26',
                'updated_at' => '2021-01-24 07:59:24',
                'status' => 0
            ],
            [
                'id' => 19,
                'nombre' => 'Osvaldo Veloz',
                'email' => 'veloz_osvaldo@hotmail.com',
                'password' => '$2y$10$HVf3l2fNCCKnwUI4yoJJheLAnwFYmf3uRXazgObSkwn0viwPNPlYi',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => 'Ys1z7BTbruLbEcon9JKTFU97xMkyvhQco3kSxjtcafJCYs7viCzvfYYWfQQc',
                'created_at' => '2021-01-24 08:14:40',
                'updated_at' => '2022-06-01 18:47:54',
                'status' => 1
            ],
            [
                'id' => 20,
                'nombre' => 'peralta',
                'email' => 'peraltagomezeduardo@gmail.com',
                'password' => '$2y$10$NrKF9TKAjX6XRB8ZRrXot.gsE4gXhnLhTseKQIsRlpeifoH0UanjW',
                'cliente_id' => 14,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2021-09-03 14:59:22',
                'updated_at' => '2024-01-18 14:34:15',
                'status' => 0
            ],
            [
                'id' => 21,
                'nombre' => 'Efraín Benitez',
                'email' => 'efrainbenitez',
                'password' => '$2y$10$cVPOjjB7MvVrIWgzmftTcemjxohZIt7e2ES2raDqCyPuBcA0XMWr.',
                'cliente_id' => 14,
                'role_id' => 3,
                'remember_token' => 'IDY2BkqCsS0TtLd1oZQBHnx6KGamPPYw4ssJCnByDFO3EdwTjxGZAZMzwJdX',
                'created_at' => '2022-04-07 04:08:22',
                'updated_at' => '2024-01-18 14:34:06',
                'status' => 0
            ],
            [
                'id' => 22,
                'nombre' => 'Ing. Sergio Trejo Dena',
                'email' => 'jona.dena@gmail.com',
                'password' => '$2y$10$uX8AJjuTkPjC4EbZQqFjRuwqyxm6E5CB5Mr.KTdAEbqc/.QbNOQkG',
                'cliente_id' => 14,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2022-04-07 04:23:28',
                'updated_at' => '2024-01-18 14:34:11',
                'status' => 0
            ],
            [
                'id' => 23,
                'nombre' => 'Armando',
                'email' => 'armando2005@hotmail.com',
                'password' => '$2y$10$sxYXrnkCIQWBYDaeQeFOMua.BQXUber0bAcKpSpCs2Ri8H57jdoSa',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => 'YwuwY4tuEUN9F4OnM5cR0eOQ6VXhLxUSBXL0fbEz0nE4oB5Zu0r2tjfHsHxk',
                'created_at' => '2022-06-01 20:49:01',
                'updated_at' => '2024-06-17 21:57:33',
                'status' => 1
            ],
            [
                'id' => 24,
                'nombre' => 'Enrique Alvaher',
                'email' => 'enriquealvaher@gmail.com',
                'password' => '$2y$10$b9M7mmT9bg31mlBLHYaKZeuPLBrDoDcOEOvJ1wZA/CD2DyBimZadO',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => 'xoXVKQL1nkFs4K02AalqNv7sECYAqF1bo1F7T8lKFtELqnkS2h0tHYA42lQ1',
                'created_at' => '2022-06-01 20:49:31',
                'updated_at' => '2022-12-06 00:37:24',
                'status' => 1
            ],
            [
                'id' => 25,
                'nombre' => 'Modesto San Juanico',
                'email' => 'modestoalva159@gmail.com',
                'password' => '$2y$10$UUdR.ToEb1uVJPep7wp6t.WwOzQhVwIS0RvTXYvm3GHu48AcSAMZ6',
                'cliente_id' => 13,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2022-08-05 15:31:15',
                'updated_at' => '2022-08-05 15:31:15',
                'status' => 1
            ],
            [
                'id' => 26,
                'nombre' => 'Raúl Martínez Trejo Luna',
                'email' => 'rmtrejoluna@gmail.com',
                'password' => '$2y$10$bvLjUmXM1ENBbYTjsr3zQO5iljlk6.yy3orLK7j1GvHLb6Jx1pjF2',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-02-20 16:08:48',
                'updated_at' => '2023-02-20 16:08:48',
                'status' => 1
            ],
            [
                'id' => 27,
                'nombre' => 'Ernesto Medina',
                'email' => 'ermedinan@hotmail.com',
                'password' => '$2y$10$habSOKk9oSczkCSu59nMLuSJFm9x1tYRSBIFD4rUnqMNMTrG0n0fO',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => 'nJvG41NY5ViVdr4PBVpsj5cKCPQOJImEDvuC0LgtzcpQ3M340TuuUb8Goz9I',
                'created_at' => '2023-02-21 14:54:06',
                'updated_at' => '2023-02-21 14:54:06',
                'status' => 1
            ],
            [
                'id' => 28,
                'nombre' => 'Antonio Garcia',
                'email' => 'garciaa0713@hotmail.com',
                'password' => '$2y$10$kaigO0nOqI7eCMoEBzeq..mBQaNNzFd.kfht3a1fk9SR2Ec2r3fp6',
                'cliente_id' => 14,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-03-28 18:05:45',
                'updated_at' => '2024-02-16 02:46:11',
                'status' => 0
            ],
            [
                'id' => 29,
                'nombre' => 'Ramón de Alba Martín',
                'email' => 'chamacueroramon@hotmail.com',
                'password' => '$2y$10$aAI2EUTBjhMMBXumR3ybHeLt/j4afE4za.EkAXICVbGCyJOCLHAC2',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-04-05 15:23:48',
                'updated_at' => '2023-04-05 15:23:48',
                'status' => 1
            ],
            [
                'id' => 30,
                'nombre' => 'Victor Alfonso Gómez Gómez',
                'email' => 'vg235590@gmail.com',
                'password' => '$2y$10$KwQlifUY505MwRe/mHU.c.0H9vWdkG3xSNb65OiztUOiy66fcS/DO',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-04-05 15:25:44',
                'updated_at' => '2023-04-05 15:25:44',
                'status' => 1
            ],
            [
                'id' => 31,
                'nombre' => 'Jose Franco Delgadillo',
                'email' => 'francodelgadillojose@gmail.com',
                'password' => '$2y$10$i0UB/.k3fzu/o3FD1Um32ugdu9GfAtJV4fYVHrSLkeQoD1LayyVfC',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-04-05 15:26:34',
                'updated_at' => '2023-04-05 15:26:34',
                'status' => 1
            ],
            [
                'id' => 32,
                'nombre' => 'Ricardo Marquez Rocha',
                'email' => 'marquez9413r@gmail.com',
                'password' => '$2y$10$Otr8iqAle7sMhEfIVbrIHuaVh7zkaWZovtJ/SC9ohzOX6J8IN8MYC',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-04-05 15:27:12',
                'updated_at' => '2023-04-05 15:27:12',
                'status' => 1
            ],
            [
                'id' => 33,
                'nombre' => 'Emmanuel de Jesús Gómez González',
                'email' => 'ispemmanuel.gomez@gmail.com',
                'password' => '$2y$10$4kpcHco0aw2VPnhzukOxae3Fw5oPdA2.PCmvLOdZA.vb0tVa2WT7i',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-04-05 15:28:24',
                'updated_at' => '2023-04-05 15:28:24',
                'status' => 1
            ],
            [
                'id' => 34,
                'nombre' => 'Andrés Ramírez Anaya',
                'email' => 'isp.andres.ra@gmail.com',
                'password' => '$2y$10$MYcLJ5p5Xk3U3i4NxfLo4OvAak.Xq5omirDu/dpeeJPlDxD/9xlqK',
                'cliente_id' => 16,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-04-05 15:29:31',
                'updated_at' => '2023-04-05 15:29:31',
                'status' => 1
            ],
            [
                'id' => 35,
                'nombre' => 'Rancho San José',
                'email' => 'ranchossanjose1@gmail.com',
                'password' => '$2y$10$RoqwnEGOg7hTyLPOcszNJeLrPoS5Ui6QW/MSFtanci/MRP2vl5b7e',
                'cliente_id' => 17,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-07-10 16:29:47',
                'updated_at' => '2023-07-20 17:15:00',
                'status' => 1
            ],
            [
                'id' => 36,
                'nombre' => 'Prueba',
                'email' => 'Prueba@aguacatesazteca.com',
                'password' => '$2y$10$WGhk.OURbAKfL5MfrH70/uoSj6HaS2LTxvct90VmQenDXPeQqbOk2',
                'cliente_id' => 18,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-07-13 15:18:36',
                'updated_at' => '2023-07-13 15:18:36',
                'status' => 1
            ],
            [
                'id' => 37,
                'nombre' => 'Gumer',
                'email' => 'g.moreno@aguacatesazteca.com',
                'password' => '$2y$10$0V1BvUlGt0uBp1SS4e.bxOXpbRQ8SWeycaqfYnKiObtuyV6VrOLJO',
                'cliente_id' => 18,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-07-14 15:06:25',
                'updated_at' => '2023-07-14 15:06:25',
                'status' => 1
            ],
            [
                'id' => 38,
                'nombre' => 'Carlos',
                'email' => 'cibriantovarc@gmail.com',
                'password' => '$2y$10$DtLOuQnIZGVIfkFMaHE2..mqQ9BHMGEBxRLCkjQd1XkzJ2YwMVmMa',
                'cliente_id' => 18,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2023-07-14 15:07:32',
                'updated_at' => '2023-07-17 15:39:06',
                'status' => 1
            ],
            [
                'id' => 39,
                'nombre' => 'Jesus Elvira',
                'email' => 'ica.jesus.eb@gmail.com',
                'password' => '$2y$10$vSQf2vZ8.3jmv5d4Sudnr.BhR8E0FU3JTvgSLTDDbL7aMleL7g1QK',
                'cliente_id' => 14,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2024-02-16 02:47:15',
                'updated_at' => '2024-02-16 02:47:15',
                'status' => 1
            ],
            [
                'id' => 40,
                'nombre' => 'Fabricio Aceves',
                'email' => 'fabricio@cooperativaelfresno.com',
                'password' => '$2y$10$Y03B0DlI56F.uhv0ET41W.Fg/zPIDY/A5GEExhFaRw/jPsPw00Z6u',
                'cliente_id' => 14,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2024-02-21 02:19:08',
                'updated_at' => '2024-02-21 02:19:08',
                'status' => 1
            ],
            [
                'id' => 41,
                'nombre' => 'Carlos Sa',
                'email' => 'j_carlos@cooperativaelfresno.com',
                'password' => '$2y$10$Ch9sQdPPBtfS3zI6PSEIe.ocbf20INreQvAwc07Nu6lWufqfIot32',
                'cliente_id' => 14,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2024-02-21 02:19:28',
                'updated_at' => '2024-02-21 02:19:28',
                'status' => 1
            ],
            [
                'id' => 42,
                'nombre' => 'VERIFICADOR',
                'email' => 'VERIFICADOR@AGRONORMAN.COM',
                'password' => '$2y$10$a/.yonGF4C4HSm1jczrdm.7mupv.HlD4b3JuCm4YabcEZqyPoap7S',
                'cliente_id' => 19,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2024-07-19 19:58:53',
                'updated_at' => '2024-07-19 19:58:53',
                'status' => 1
            ],
            [
                'id' => 44,
                'nombre' => 'Rodolfo Ramirez',
                'email' => 'ulises@tquis.com',
                'password' => '$2y$10$v9YHt3e4tzmNidik9NSscesr7TgeomgoV5OwH/EYKVn99UKSMOBka',
                'cliente_id' => 17,
                'role_id' => 3,
                'remember_token' => null,
                'created_at' => '2025-04-09 17:12:18',
                'updated_at' => '2025-04-09 17:12:18',
                'status' => 1
            ],
        ]);
    }
}
