<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ZonaManejosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('zona_manejos')->insert([
            [
                'id' => 3,
                'nombre' => 'Jardín Raúl',
                'parcela_id' => 4,
                'temp_base_calor' => null,
                'created_at' => '2019-07-17 00:00:00',
                'updated_at' => '2020-04-23 13:29:23',
                'status' => 1,
                'cultivo_id' => 7,
                'fecha_inicial_uca' => null,
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 4,
                'nombre' => 'Zarzamora',
                'parcela_id' => 5,
                'temp_base_calor' => null,
                'created_at' => '2019-07-17 00:00:00',
                'updated_at' => '2019-07-17 00:00:00',
                'status' => 1,
                'cultivo_id' => 9,
                'fecha_inicial_uca' => null,
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 5,
                'nombre' => 'Jitomate',
                'parcela_id' => 6,
                'temp_base_calor' => null,
                'created_at' => null,
                'updated_at' => '2021-01-22 12:42:12',
                'status' => 1,
                'cultivo_id' => 12,
                'fecha_inicial_uca' => '2021-01-20',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 6,
                'nombre' => 'Jitomate',
                'parcela_id' => 7,
                'temp_base_calor' => null,
                'created_at' => null,
                'updated_at' => '2021-01-22 12:43:13',
                'status' => 1,
                'cultivo_id' => 12,
                'fecha_inicial_uca' => '2021-01-22',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 8,
                'nombre' => 'Embalse 1',
                'parcela_id' => 13,
                'temp_base_calor' => null,
                'created_at' => '2019-07-17 00:00:00',
                'updated_at' => '2022-06-15 07:35:17',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2019-01-01',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 9,
                'nombre' => 'Barranca 1',
                'parcela_id' => 13,
                'temp_base_calor' => null,
                'created_at' => '2019-07-17 00:00:00',
                'updated_at' => '2022-06-15 07:35:09',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2020-08-27',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 10,
                'nombre' => 'Entrada 1',
                'parcela_id' => 13,
                'temp_base_calor' => null,
                'created_at' => '2019-07-17 00:00:00',
                'updated_at' => '2022-06-15 07:35:27',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2019-01-01',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 11,
                'nombre' => 'Jesus Elvira',
                'parcela_id' => 16,
                'temp_base_calor' => 7,
                'created_at' => '2020-01-27 00:00:00',
                'updated_at' => '2022-12-18 13:54:33',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2020-08-27',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 4,
                'fecha_siembra' => '2022-01-01',
                'objetivo_produccion' => 1
            ],
            [
                'id' => 12,
                'nombre' => 'Jesus Elvira',
                'parcela_id' => 17,
                'temp_base_calor' => null,
                'created_at' => '2020-01-27 00:00:00',
                'updated_at' => '2020-04-23 13:02:35',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2020-08-27',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 18,
                'nombre' => 'prueba 1',
                'parcela_id' => 23,
                'temp_base_calor' => null,
                'created_at' => '2020-05-18 16:43:54',
                'updated_at' => '2020-05-18 16:43:54',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => null,
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 19,
                'nombre' => 'Higo',
                'parcela_id' => 6,
                'temp_base_calor' => 5,
                'created_at' => '2020-07-31 16:58:34',
                'updated_at' => '2022-06-01 07:07:21',
                'status' => 1,
                'cultivo_id' => 19,
                'fecha_inicial_uca' => '2021-01-21',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 20,
                'nombre' => 'Ladera',
                'parcela_id' => 26,
                'temp_base_calor' => null,
                'created_at' => '2020-10-22 12:58:00',
                'updated_at' => '2020-10-22 12:58:00',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2020-04-01',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 23,
                'nombre' => 'Meteorológica Santo Domingo',
                'parcela_id' => 28,
                'temp_base_calor' => 7,
                'created_at' => '2021-01-19 15:09:11',
                'updated_at' => '2024-05-06 17:23:43',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2021-12-09',
                'tipo_suelo_id' => 11,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-02-28',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 25,
                'nombre' => 'Estación dañada',
                'parcela_id' => 28,
                'temp_base_calor' => null,
                'created_at' => '2021-01-19 15:22:42',
                'updated_at' => '2021-12-17 12:04:23',
                'status' => 0,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2021-12-09',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 26,
                'nombre' => 'Higo',
                'parcela_id' => 7,
                'temp_base_calor' => null,
                'created_at' => '2021-01-22 12:44:23',
                'updated_at' => '2021-01-22 12:44:23',
                'status' => 1,
                'cultivo_id' => 19,
                'fecha_inicial_uca' => '2021-01-22',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 28,
                'nombre' => 'Pivote 20',
                'parcela_id' => 29,
                'temp_base_calor' => null,
                'created_at' => '2021-06-23 10:19:33',
                'updated_at' => '2021-12-17 11:57:02',
                'status' => 0,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2021-12-09',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 30,
                'nombre' => 'Pivote 26',
                'parcela_id' => 29,
                'temp_base_calor' => null,
                'created_at' => '2021-07-07 10:28:06',
                'updated_at' => '2021-07-07 10:28:06',
                'status' => 0,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2021-07-07',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 31,
                'nombre' => 'NPK',
                'parcela_id' => 31,
                'temp_base_calor' => 7,
                'created_at' => '2021-07-29 16:44:37',
                'updated_at' => '2024-09-20 11:22:12',
                'status' => 1,
                'cultivo_id' => 11,
                'fecha_inicial_uca' => '2024-01-01',
                'tipo_suelo_id' => 6,
                'edad_cultivo' => 3,
                'fecha_siembra' => '2022-01-03',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 32,
                'nombre' => 'Borregas',
                'parcela_id' => 32,
                'temp_base_calor' => 24,
                'created_at' => '2021-09-01 17:33:29',
                'updated_at' => '2024-05-24 10:29:19',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2021-09-01',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 15,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 33,
                'nombre' => 'Lagunitas Sur',
                'parcela_id' => 34,
                'temp_base_calor' => 10,
                'created_at' => '2022-04-07 09:48:00',
                'updated_at' => '2024-06-28 06:08:10',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2022-04-07',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 7,
                'fecha_siembra' => null,
                'objetivo_produccion' => 10
            ],
            [
                'id' => 34,
                'nombre' => 'Mendez',
                'parcela_id' => 36,
                'temp_base_calor' => 10,
                'created_at' => '2022-04-07 09:50:36',
                'updated_at' => '2024-06-27 09:26:51',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2024-02-16',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 12,
                'fecha_siembra' => null,
                'objetivo_produccion' => 10
            ],
            [
                'id' => 35,
                'nombre' => 'El Colorín',
                'parcela_id' => 35,
                'temp_base_calor' => 10,
                'created_at' => '2022-04-07 09:51:25',
                'updated_at' => '2024-06-27 09:25:34',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2022-04-07',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 8,
                'fecha_siembra' => null,
                'objetivo_produccion' => 10
            ],
            [
                'id' => 36,
                'nombre' => 'Zona 1 Mesa de Lobos',
                'parcela_id' => 37,
                'temp_base_calor' => 10,
                'created_at' => '2022-04-07 09:52:07',
                'updated_at' => '2024-05-24 10:37:34',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2022-04-07',
                'tipo_suelo_id' => 7,
                'edad_cultivo' => 4,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 37,
                'nombre' => 'Zona dañada',
                'parcela_id' => 13,
                'temp_base_calor' => null,
                'created_at' => '2022-04-07 12:07:44',
                'updated_at' => '2022-04-07 12:07:44',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2022-04-07',
                'tipo_suelo_id' => null,
                'edad_cultivo' => null,
                'fecha_siembra' => null,
                'objetivo_produccion' => 1
            ],
            [
                'id' => 38,
                'nombre' => 'Meteorológica San Juanico',
                'parcela_id' => 38,
                'temp_base_calor' => 7,
                'created_at' => '2022-05-28 08:20:18',
                'updated_at' => '2024-05-06 17:23:12',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2022-05-14',
                'tipo_suelo_id' => 2,
                'edad_cultivo' => null,
                'fecha_siembra' => '2022-09-16',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 39,
                'nombre' => 'Meteorológica San Felipe',
                'parcela_id' => 29,
                'temp_base_calor' => 7,
                'created_at' => '2022-05-28 08:57:32',
                'updated_at' => '2024-08-30 10:09:41',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2022-05-14',
                'tipo_suelo_id' => 3,
                'edad_cultivo' => 2,
                'fecha_siembra' => '2022-08-10',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 40,
                'nombre' => 'Pivote Agua Sucia',
                'parcela_id' => 29,
                'temp_base_calor' => 7,
                'created_at' => '2022-07-13 10:08:34',
                'updated_at' => '2024-08-30 10:11:10',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2022-07-11',
                'tipo_suelo_id' => 4,
                'edad_cultivo' => null,
                'fecha_siembra' => '2022-07-12',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 41,
                'nombre' => 'Atmosférica Escuela Nacional de Lechería',
                'parcela_id' => 39,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 10:49:55',
                'updated_at' => '2023-12-26 20:59:03',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-07-02',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-07-02',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 42,
                'nombre' => 'NPK Escuela Nacional de Lecheria',
                'parcela_id' => 39,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 12:44:46',
                'updated_at' => '2023-12-21 12:11:25',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-07-02',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-07-02',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 43,
                'nombre' => 'Atmosferica Alto de Barajas',
                'parcela_id' => 40,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:01:26',
                'updated_at' => '2023-12-21 11:14:01',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-29',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-29',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 44,
                'nombre' => 'NPK Alto de Barajas',
                'parcela_id' => 40,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:02:07',
                'updated_at' => '2023-12-21 11:30:11',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-29',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-29',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 45,
                'nombre' => 'NPK Bioagrofert',
                'parcela_id' => 41,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:39:07',
                'updated_at' => '2023-12-21 11:57:41',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-05',
                'tipo_suelo_id' => 6,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-05',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 46,
                'nombre' => 'Atmosferica BioAgrofert',
                'parcela_id' => 41,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:39:58',
                'updated_at' => '2023-12-21 11:57:46',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-05',
                'tipo_suelo_id' => 6,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-05',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 47,
                'nombre' => 'NPK Agua Limpia',
                'parcela_id' => 42,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:41:09',
                'updated_at' => '2023-12-21 11:56:07',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-05-18',
                'tipo_suelo_id' => 4,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-05-18',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 48,
                'nombre' => 'Atmosferica El Bajio',
                'parcela_id' => 42,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:41:56',
                'updated_at' => '2023-07-12 09:23:53',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-02-16',
                'tipo_suelo_id' => 4,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-05-18',
                'objetivo_produccion' => 15
            ],
            [
                'id' => 49,
                'nombre' => 'Atmosferica San Juanico',
                'parcela_id' => 44,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:43:10',
                'updated_at' => '2023-12-21 11:52:42',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-05-17',
                'tipo_suelo_id' => 3,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-05-17',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 50,
                'nombre' => 'NPK San Juanico',
                'parcela_id' => 44,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:44:04',
                'updated_at' => '2023-12-21 11:54:03',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-05-17',
                'tipo_suelo_id' => 4,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-05-17',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 51,
                'nombre' => 'Atmosferica Tepatitlán',
                'parcela_id' => 45,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:45:13',
                'updated_at' => '2023-12-21 12:07:30',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-29',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-29',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 52,
                'nombre' => 'NPK Tepatitlán',
                'parcela_id' => 45,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:46:07',
                'updated_at' => '2023-12-21 12:09:00',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-29',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-29',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 53,
                'nombre' => 'Atmosferica San Miguel',
                'parcela_id' => 46,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:47:05',
                'updated_at' => '2023-12-21 12:03:52',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-29',
                'tipo_suelo_id' => 2,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-29',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 54,
                'nombre' => 'NPK San Miguel',
                'parcela_id' => 46,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:48:02',
                'updated_at' => '2023-12-21 12:04:56',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-29',
                'tipo_suelo_id' => 11,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-29',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 55,
                'nombre' => 'NPK Fco. Marquez',
                'parcela_id' => 47,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:51:41',
                'updated_at' => '2023-12-21 12:02:12',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-22',
                'tipo_suelo_id' => 9,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-22',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 56,
                'nombre' => 'Atmosferica Fco. Marquez',
                'parcela_id' => 47,
                'temp_base_calor' => 7,
                'created_at' => '2023-02-17 13:52:58',
                'updated_at' => '2023-12-21 12:00:51',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-06-22',
                'tipo_suelo_id' => 9,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-06-22',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 57,
                'nombre' => 'Atmosferica El Bajio',
                'parcela_id' => 43,
                'temp_base_calor' => 10,
                'created_at' => '2023-03-14 12:05:48',
                'updated_at' => '2023-03-14 12:05:48',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-02-16',
                'tipo_suelo_id' => 7,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-02-16',
                'objetivo_produccion' => 1
            ],
            [
                'id' => 58,
                'nombre' => 'NPK El Bajio',
                'parcela_id' => 43,
                'temp_base_calor' => 10,
                'created_at' => '2023-03-14 12:06:39',
                'updated_at' => '2023-03-14 12:06:39',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-02-16',
                'tipo_suelo_id' => 10,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-03-16',
                'objetivo_produccion' => 1
            ],
            [
                'id' => 59,
                'nombre' => 'Zona 7',
                'parcela_id' => 47,
                'temp_base_calor' => 10,
                'created_at' => '2023-07-10 11:26:37',
                'updated_at' => '2024-11-26 08:41:28',
                'status' => 1,
                'cultivo_id' => 9,
                'fecha_inicial_uca' => '2023-07-10',
                'tipo_suelo_id' => 6,
                'edad_cultivo' => 3,
                'fecha_siembra' => '2023-07-10',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 60,
                'nombre' => 'Atmosferica Agualimpia Nueva',
                'parcela_id' => 42,
                'temp_base_calor' => 10,
                'created_at' => '2023-07-12 10:13:15',
                'updated_at' => '2023-12-21 11:56:03',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2023-05-18',
                'tipo_suelo_id' => 3,
                'edad_cultivo' => null,
                'fecha_siembra' => '2023-05-18',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 61,
                'nombre' => 'Loma el Mezquite',
                'parcela_id' => 47,
                'temp_base_calor' => 10,
                'created_at' => '2023-07-13 09:55:57',
                'updated_at' => '2024-05-03 12:08:25',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2023-07-15',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => 1,
                'fecha_siembra' => '2023-07-15',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 62,
                'nombre' => 'Tabla 1',
                'parcela_id' => 47,
                'temp_base_calor' => 10,
                'created_at' => '2024-01-12 13:20:19',
                'updated_at' => '2024-07-05 12:28:45',
                'status' => 1,
                'cultivo_id' => 9,
                'fecha_inicial_uca' => '2024-05-02',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 3,
                'fecha_siembra' => '2024-01-12',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 63,
                'nombre' => 'Lolitas Sur',
                'parcela_id' => 36,
                'temp_base_calor' => 10,
                'created_at' => '2024-02-15 20:45:47',
                'updated_at' => '2024-06-28 06:06:29',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2024-02-16',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 4,
                'fecha_siembra' => '2024-02-14',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 64,
                'nombre' => 'Lagunitas ER',
                'parcela_id' => 34,
                'temp_base_calor' => 24,
                'created_at' => '2024-05-24 10:32:21',
                'updated_at' => '2024-05-24 10:45:25',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2024-05-01',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 7,
                'fecha_siembra' => '2014-06-21',
                'objetivo_produccion' => 1
            ],
            [
                'id' => 65,
                'nombre' => 'Lolitas Sur (2)',
                'parcela_id' => 36,
                'temp_base_calor' => 24,
                'created_at' => '2024-05-24 10:46:38',
                'updated_at' => '2024-06-27 09:26:26',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2024-05-01',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => null,
                'fecha_siembra' => '2014-06-21',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 66,
                'nombre' => 'Pirata',
                'parcela_id' => 36,
                'temp_base_calor' => 24,
                'created_at' => '2024-05-24 10:47:35',
                'updated_at' => '2024-06-17 12:10:30',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2024-05-01',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 5,
                'fecha_siembra' => '2014-06-21',
                'objetivo_produccion' => 12
            ],
            [
                'id' => 67,
                'nombre' => 'Borregas',
                'parcela_id' => 36,
                'temp_base_calor' => 24,
                'created_at' => '2024-05-24 10:48:26',
                'updated_at' => '2024-06-17 12:10:14',
                'status' => 1,
                'cultivo_id' => 8,
                'fecha_inicial_uca' => '2024-05-01',
                'tipo_suelo_id' => 1,
                'edad_cultivo' => 10,
                'fecha_siembra' => '2014-06-21',
                'objetivo_produccion' => 12
            ],
            [
                'id' => 68,
                'nombre' => 'Convencional',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-06-17 12:15:22',
                'updated_at' => '2024-08-30 10:05:48',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-06-01',
                'tipo_suelo_id' => 10,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-06-01',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 69,
                'nombre' => 'NORMAN',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-06-17 12:16:03',
                'updated_at' => '2024-08-30 10:08:09',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-06-08',
                'tipo_suelo_id' => 10,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-06-08',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 70,
                'nombre' => 'Norman-Solena',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-06-17 12:17:08',
                'updated_at' => '2024-08-30 10:08:31',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-06-08',
                'tipo_suelo_id' => 10,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-06-08',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 71,
                'nombre' => 'EST 823009',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-07-19 12:48:25',
                'updated_at' => '2024-07-24 15:14:41',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-07-01',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-07-01',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 72,
                'nombre' => 'EST 603542',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-07-19 12:52:18',
                'updated_at' => '2024-07-24 15:17:12',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-07-01',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-07-01',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 73,
                'nombre' => 'EST 836456',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-07-19 12:53:22',
                'updated_at' => '2024-08-30 10:35:38',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-07-01',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-07-01',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 74,
                'nombre' => 'EST 605935',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-07-19 12:54:05',
                'updated_at' => '2024-08-30 10:37:01',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-07-01',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-07-01',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 75,
                'nombre' => 'EST 834840',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-07-19 12:54:52',
                'updated_at' => '2024-08-30 10:37:36',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-07-01',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-07-01',
                'objetivo_produccion' => 10
            ],
            [
                'id' => 76,
                'nombre' => 'Avansys',
                'parcela_id' => 47,
                'temp_base_calor' => 24,
                'created_at' => '2024-07-19 13:42:19',
                'updated_at' => '2024-07-19 13:42:19',
                'status' => 1,
                'cultivo_id' => 13,
                'fecha_inicial_uca' => '2024-07-01',
                'tipo_suelo_id' => 8,
                'edad_cultivo' => null,
                'fecha_siembra' => '2024-07-01',
                'objetivo_produccion' => 1
            ]
        ]);
    }
}
